# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demirbas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demirbasadi', models.CharField(max_length=200)),
                ('bolum', models.CharField(max_length=200)),
                ('modeli', models.TextField()),
                ('durum', models.CharField(choices=[('A', 'Aktif'), ('P', 'Pasif')], max_length=1)),
                ('garanti_bitis', models.DateField()),
                ('amts_kalanyil', models.PositiveIntegerField()),
                ('env_bedeli', models.IntegerField()),
                ('aciklama', models.TextField()),
                ('yetkinlik_skalasi', models.CharField(max_length=1)),
                ('yaratildi', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='musteri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_adi', models.TextField(max_length=200)),
                ('fat_turu', models.CharField(choices=[('S', 'SabitÜcret'), ('P', 'ProjeSaati'), ('G', 'GörevSaati')], max_length=1)),
                ('fat_durumu', models.CharField(choices=[('B', 'Başlamadı'), ('D', 'DevamEdiyor'), ('X', 'Beklemede'), ('I', 'İptal'), ('T', 'Tamamlandı')], max_length=1)),
                ('toplam_ucret', models.IntegerField()),
                ('aciklama', models.TextField()),
                ('yaratildi', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giris.musteri')),
            ],
        ),
        migrations.AddField(
            model_name='demirbas',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giris.kategori'),
        ),
        migrations.AddField(
            model_name='demirbas',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giris.marka'),
        ),
        migrations.AddField(
            model_name='demirbas',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giris.proje'),
        ),
    ]
