# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demirbas',
            name='aciklama',
            field=models.TextField(verbose_name='Açıklama:'),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='amts_kalanyil',
            field=models.PositiveIntegerField(verbose_name='Kalan amts yılı:'),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='bolum',
            field=models.CharField(max_length=200, verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='demirbasadi',
            field=models.CharField(max_length=200, verbose_name='Demirbaş Adı:'),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='env_bedeli',
            field=models.IntegerField(verbose_name='Envanter Bedeli:'),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='garanti_bitis',
            field=models.DateField(verbose_name='Garanti bitiş:'),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='modeli',
            field=models.CharField(max_length=200, verbose_name='Modeli'),
        ),
    ]
