# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0003_deneme_giris'),
    ]

    operations = [
        migrations.CreateModel(
            name='alt_kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_kategori_adi', models.CharField(max_length=200)),
                ('kategorisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='ariza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ariza_adi', models.CharField(max_length=200)),
                ('tutar', models.PositiveIntegerField()),
                ('aciklama', models.TextField()),
                ('yaratildi', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ekipman_turu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekipman_turu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='grup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='hareket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('har_tipi', models.CharField(choices=[('T', 'Taşıma'), ('D', 'Depoya Taşı'), ('P', 'Pert'), ('G', 'Depodan Taşı'), ('X', 'Pert İptal'), ('Z', 'Proje Sonrası Verildi')], max_length=1)),
                ('aciklama', models.TextField()),
                ('yaratildi', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='servis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servis_adi', models.CharField(max_length=200)),
                ('mail_adresi', models.EmailField(max_length=254)),
                ('kisi_adi', models.CharField(max_length=200)),
                ('kisi_soyadi', models.CharField(max_length=200)),
                ('yaratildi', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='sirket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_adi', models.CharField(max_length=200)),
                ('grubu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.grup')),
            ],
        ),
        migrations.CreateModel(
            name='yedek_parca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yparca_adi', models.CharField(max_length=200)),
                ('alt_kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.alt_kategori')),
            ],
        ),
        migrations.RemoveField(
            model_name='demirbas',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='demirbas',
            name='yetkinlik_skalasi',
        ),
        migrations.AddField(
            model_name='demirbas',
            name='gar_varmi',
            field=models.CharField(choices=[('E', 'Evet'), ('H', 'Hayır')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='proje',
            name='ili',
            field=models.CharField(choices=[('ANK', 'Ankara'), ('IST', 'İstanbul'), ('IZM', 'İzmir'), ('ADA', 'Adana'), ('BUR', 'Bursa'), ('KON', 'Konya'), ('KAY', 'Kayseri'), ('MER', 'Mersin'), ('ANT', 'Antalya'), ('SAM', 'Samsun'), ('TRA', 'Trabzon'), ('MAL', 'Malatya')], default='ANK', max_length=3),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='aciklama',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='amts_kalanyil',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='bolum',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='demirbasadi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='env_bedeli',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='garanti_bitis',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.marka'),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='modeli',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.proje'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='musteri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.musteri'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='toplam_ucret',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='hareket',
            name='demirbas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.demirbas'),
        ),
        migrations.AddField(
            model_name='hareket',
            name='mevcut_proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_project', to='giris.proje'),
        ),
        migrations.AddField(
            model_name='hareket',
            name='sonraki_proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='next_project', to='giris.proje'),
        ),
        migrations.AddField(
            model_name='ariza',
            name='demirbas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.demirbas'),
        ),
        migrations.AddField(
            model_name='ariza',
            name='servis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.servis'),
        ),
        migrations.AddField(
            model_name='ariza',
            name='yedek_parca_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='ilk_parca', to='giris.yedek_parca'),
        ),
        migrations.AddField(
            model_name='ariza',
            name='yedek_parca_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='ikinci_parca', to='giris.yedek_parca'),
        ),
        migrations.AddField(
            model_name='ariza',
            name='yedek_parca_3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='ucuncu_parca', to='giris.yedek_parca'),
        ),
        migrations.AddField(
            model_name='ariza',
            name='yedek_parca_4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='dorduncu_parca', to='giris.yedek_parca'),
        ),
        migrations.AddField(
            model_name='ariza',
            name='yedek_parca_5',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='besinci_parca', to='giris.yedek_parca'),
        ),
    ]
