# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0005_auto_20170930_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demirbas',
            name='alt_kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='giris.alt_kategori'),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='ekipman_turu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='giris.ekipman_turu'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='sirket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='giris.sirket'),
        ),
    ]
