# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0006_auto_20170930_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='demirbas',
            name='kullanici',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='alt_kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.alt_kategori'),
        ),
        migrations.AlterField(
            model_name='demirbas',
            name='ekipman_turu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.ekipman_turu'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.sirket'),
        ),
    ]
