# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0007_auto_20170930_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='kayit_acilis',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ariza',
            name='kayit_kapanis',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ariza',
            name='kullanici',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='hareket',
            name='kullanici',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
