# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0008_auto_20171004_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demirbas',
            name='garanti_bitis',
        ),
    ]
