# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0009_remove_demirbas_garanti_bitis'),
    ]

    operations = [
        migrations.AddField(
            model_name='demirbas',
            name='garanti_bitis',
            field=models.DateField(blank=True, null=True),
        ),
    ]
