# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0010_demirbas_garanti_bitis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demirbas',
            name='garanti_bitis',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
    ]
