# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0011_auto_20171005_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hareket',
            name='demirbas',
        ),
        migrations.AddField(
            model_name='hareket',
            name='demirbas_adi',
            field=models.CharField(default='demirbas', max_length=100),
        ),
        migrations.AddField(
            model_name='hareket',
            name='demirbas_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='giris.demirbas'),
        ),
    ]
