# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0012_auto_20171006_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='yedek_parca_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ilk_parca', to='giris.yedek_parca'),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='yedek_parca_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ikinci_parca', to='giris.yedek_parca'),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='yedek_parca_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ucuncu_parca', to='giris.yedek_parca'),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='yedek_parca_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dorduncu_parca', to='giris.yedek_parca'),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='yedek_parca_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='besinci_parca', to='giris.yedek_parca'),
        ),
        migrations.AlterField(
            model_name='hareket',
            name='demirbas_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giris.demirbas'),
        ),
    ]
