# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-15 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0013_auto_20171010_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='yp_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yp_choice', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='ariza',
            name='kayit_acilis',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='kayit_kapanis',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
