# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0017_dem_ariza_alt_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='dem_ariza',
            name='idisi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='giris.demirbas'),
            preserve_default=False,
        ),
    ]
