# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0018_dem_ariza_idisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='proje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='giris.proje'),
            preserve_default=False,
        ),
    ]
