# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0019_ariza_proje'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='kullanici',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
