# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0020_proje_kullanici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='proje_adi',
            field=models.CharField(max_length=200),
        ),
    ]
