# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giris', '0021_auto_20171030_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ariza',
            name='kullanici',
        ),
        migrations.RemoveField(
            model_name='demirbas',
            name='kullanici',
        ),
        migrations.RemoveField(
            model_name='hareket',
            name='kullanici',
        ),
        migrations.RemoveField(
            model_name='proje',
            name='kullanici',
        ),
        migrations.RemoveField(
            model_name='proje',
            name='yaratildi',
        ),
        migrations.AddField(
            model_name='ariza',
            name='kullanan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demirbas',
            name='kimin',
            field=models.CharField(choices=[('Ş', 'ŞİRKETİN'), ('M', 'MÜŞTERİNİN')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demirbas',
            name='kullanan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demirbas',
            name='kullanim_durumu',
            field=models.CharField(choices=[('K', 'Kullanımda'), ('P', 'Pert oldu'), ('V', 'Proje sonunda müşteriye verildi'), ('D', 'Depoda')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hareket',
            name='kullanan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
